### ISSUE TITLE
Metafield translations missing?

### ISSUE THREAD

**Issue by AlexanderProd** [fedehub93/gatsby-source-shopify-translations#5]
Hi, 

I'm wondering if metafield translations are not available (yet) or if I just don find them. 
I've been looking trough the GraphiQL explorer and examined the Metafield types but the don't contain the locale filter.

When I query the `shopifyProductMetafield` type I always get the default language. I have translated my Metafields using the Etranslate Shopify App. 

Greetings 
Alexander

**Comment by fedehub93** [comment]
Hi Alexander,
I accepted your pull request in the morning but I have seen in the shopify docs that is not so simple with metafields.

I use Storefront API in the plugin to retrieve translations becouse I saw it's the right way using **Accept-Language** key in the header request with the correct locale as a value.

_meteafields_ is a field in product but is not available in the Storefront API, but only in Admin API.

In Storefront API is available _metafield_ field which needs 2 arguments to work, **key** and **namespace**. Then return only metafields for these arguments.

[Storefront API - Product Object ](https://shopify.dev/api/storefront/2022-01/objects/Product#fields)

This would be a different behavior to adopt but there are an other problem.

The Storefront API have not access to this field (metafield) by default, in fact, from shopify documentation: 

[Expose metafields in Storefront API to be read](https://shopify.dev/api/examples/metafields#expose-metafields-to-the-storefront-api)

_By default, the Storefront API can't read metafields. To expose specific metafields to the Storefront API, you need to use the GraphQL Admin API. For each metafield that you want to expose, you need to create a [MetafieldStorefrontVisibility](https://shopify.dev/api/admin/graphql/reference/metafields/metafieldstorefrontvisibility) record._

I've spent some time doing some research and it's not so trivial at present to obtain the translations of the Metafields.

Thanks for the contribution

**Comment by AlexanderProd** [comment]
Oh that’s interesting because the way I implemented it, it worked with my store and also translated. Is this because the plug-in is using the admin api?

**Comment by fedehub93** [comment]
Ok I understand,
in Shopify, on the single metafield settings I had not the correct access rights. I set these and now I see the correct response with Postman and Shopify GraphQL App but still not in my gatsby app.

It's a weird behavior, I probably still have something wrong with my Gatsby app.
However, the graphql query is correct.

Thanks again for the contribution.

**Comment by fedehub93** [comment]
Ok, now with api version "2022-01" it works for me.
